# Generated by Django 2.2.18 on 2021-11-04 20:57

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم بالكامل')),
                ('mobile', models.IntegerField(blank=True, max_length=11, null=True, verbose_name='رقم الموبيل')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=5, verbose_name='النوع')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='السؤال')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='user_question.Question')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_one', to='user_question.QuestionAnswer')),
                ('answer_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_three', to='user_question.QuestionAnswer')),
                ('answer_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_two', to='user_question.QuestionAnswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user_question.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user_question.CustomUser')),
            ],
        ),
    ]
