# Generated by Django 2.2.18 on 2021-11-05 21:39

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=5, null=True, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(default=93672918736, max_length=11, verbose_name='رقم الموبيل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userquestionanswer',
            name='answer_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_one', to='user_question.QuestionAnswer'),
        ),
        migrations.AlterField(
            model_name='userquestionanswer',
            name='answer_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_three', to='user_question.QuestionAnswer'),
        ),
        migrations.AlterField(
            model_name='userquestionanswer',
            name='answer_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_two', to='user_question.QuestionAnswer'),
        ),
    ]
